version: '3'
services:
  frontend:
    build: ./frontend
    restart: always
    ports:
      - '3000:3000'
  backend:
    build: ./api
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - '5555:5555'  
  mysql:
    image: mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    environment:
      - MYSQL_PASSWORD=sqlpassword
      - MYSQL_DATABASE=time_db
  adminer:
    image: adminer  
    restart: always  
    ports: 
      - '8888:8080'  