version: '3'
services:
  frontend:
    build: ./frontend
    restart: always
    ports:
      - '3333:3000'
  backend:
    build: ./api
    restart: always
    depends_on:
      - mysql
    ports:
      - '5555:5000'  
  mysql:
    image: mysql
    restart: always
    environment:
      - MYSQL_PASSWORD=sqlpassword
      - MYSQL_DATABASE=time_db
  adminer:
    image: adminer  
    restart: always  
    ports: 
      - '8888:8080'  